chore : assignmnet-6

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -2,9 +2,8 @@ name: CI Assignment 6
 
 on:
   pull_request:
-    types:
-      - synchronize
-      - opened
+    types: [opened, synchronize, reopened]
+
     paths:
       - "packages/assignment-6/**"
 
@@ -16,6 +15,7 @@ jobs:
       - uses: pnpm/action-setup@v4
         with:
           version: latest
+
       - uses: actions/setup-node@v4
         with:
           node-version: 20
@@ -25,38 +25,82 @@ jobs:
         run: pnpm install
 
       - name: tsc && build
-        run: pnpm -F assignment-6 pnpm run build
+        id: build
+        run: pnpm -F assignment-6 build 2> error.log
 
       - name: Comment PR
-        uses: actions/github-script@v6
         if: failure()
+        uses: actions/github-script@v6.4.0
         with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
+          github-token: ${{secrets.TOKEN_FOR_CI}}
           script: |
+            const fs = require('fs')
+            const errorLog = fs.readFileSync('error.log', 'utf8')
+
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: 'Build failed for Assignment 6. Please check the build logs for more details.'
+              body: errorLog
             })
 
   lint:
     runs-on: ubuntu-latest
     steps:
-      - name: job2 구현
-        run: echo "job2의 내용을 구현해주세요"
+      - uses: actions/checkout@v4
+      - uses: pnpm/action-setup@v4
+        with:
+          version: latest
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
+
+      - name: Install dependencies
+        run: pnpm install
 
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: job3 구현
-        run: echo "job3의 내용을 구현해주세요"
+      - uses: actions/checkout@v4
+      - uses: pnpm/action-setup@v4
+        with:
+          version: latest
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: run test
+        run: pnpm -F assignment-6 run test
 
   lighthouse:
     runs-on: ubuntu-latest
     steps:
-      - name: job4 구현
-        run: echo "job4의 내용을 구현해주세요"
+      - uses: actions/checkout@v4
+      - uses: pnpm/action-setup@v4
+        with:
+          version: latest
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: Run Lighthouse CI
+        run: |
+          pnpm i -g @lhci/cli
+          pnpm -F assignment-6 lhci || echo "Fail to Run Lighthouse CI!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.TOKEN_FOR_CI}}
 
   assign_reviewer:
     runs-on: ubuntu-latest
